module.exports = {
    PAGE_SIZE: 3,
    DEFAULT_AMBULANCE_STATUS: "CONFIRMING",
    ACTIVE_AMBULANCE_STATUS: "ACTIVE",
    DEACTIVE_AMBULANCE_STATUS: "DEACTIVE",
    PROCESSING_REQUEST_STATUS: "PROCESSING",
    CANCELED_REQUEST_STATUS: "CANCELED",
    SUCCESS_REQUEST_STATUS: "SUCCESS",
    FAIL_REQUEST_STATUS: "FAIL",
    PICKED_PATIENT_STATUS: "picked",
    FINISHED_REQUEST_STATUS: "finished",
    REJECTED_REQUEST_STATUS: "rejected",
    CANCELED_REASON: "Bị hủy bởi người gửi yêu cầu",
    ACTIVE: "Đang hoạt động",
    DEACTIVE: "Ngưng hoạt động",
    CONFIRMING: "Chờ xác nhận",
    ROLE_REQUESTER: 1,
    ROLE_DRIVER: 2,
    APPROVE_REGISTER_AMBULANCE: "approved",
    REJECT_REGISTER_AMBULANCE: "rejected",
    DEFAULT_SETTING: { distance: 100, home: true, emergency: true },
    REJECTED_REASON: "Hệ thống không tìm được tài xế thích hợp"
};
