module.exports = {
    PAGE_SIZE: 8,
    DEFAULT_AMBULANCE_STATUS: "CONFIRMING",
    ACTIVE_AMBULANCE_STATUS: "ACTIVE",
    DEACTIVE_AMBULANCE_STATUS: "DEACTIVE",
    PROCESSING_REQUEST_STATUS: "PROCESSING",
    ACTIVE: "Đang hoạt động",
    DEACTIVE: "Ngưng hoạt động",
    CONFIRMING: "Chờ xác nhận"
};
